name: bus_tracker
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.7
  firebase_core: ^3.12.0
  firebase_database: ^11.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_local_notifications: ^18.0.1
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.0
  hydrated_bloc: ^10.1.1
  intl: ^0.19.0
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3
  rxdart: ^0.28.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo-tracker.png"
