name: bus_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  equatable: ^2.0.7
  firebase_core: ^3.12.0
  firebase_database: ^11.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_local_notifications: ^18.0.1
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.0
  location: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
